# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0
        with:
          flutter-version: '2.0.5'
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
#       - run: flutter test
      - run: flutter build web
      
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build/web
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
